definitions:
  notification.sendEmailRequest:
    properties:
      body:
        type: string
      recipient:
        type: string
      subject:
        type: string
    type: object
  notification.sendEmailResponse:
    properties:
      message:
        type: string
    type: object
  notification.sendSMSRequest:
    properties:
      message:
        type: string
      phoneNumber:
        type: string
    type: object
  server.Server:
    properties:
      frequency:
        type: integer
      hostname:
        type: string
      ip:
        type: string
      mailTo:
        type: string
      status:
        type: boolean
      url:
        type: string
    type: object
  sysinfo.SysInfo:
    properties:
      disk:
        type: integer
      hostname:
        type: string
      platform:
        type: string
      ram:
        type: integer
      ram available:
        type: integer
      ram free:
        type: integer
      uptime:
        type: integer
    type: object
info:
  contact: {}
paths:
  /health/check:
    get:
      consumes:
      - '*/*'
      description: get the status of server.
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties: true
            type: object
      summary: Show the status of server.
      tags:
      - root
  /health/info:
    get:
      consumes:
      - '*/*'
      description: get the info of server.
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/sysinfo.SysInfo'
      summary: Show the info of server.
      tags:
      - root
  /info/database/check:
    get:
      consumes:
      - '*/*'
      description: get the status of the database.
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties: true
            type: object
      summary: Show the status of the database.
      tags:
      - root
  /info/getFromDb:
    get:
      consumes:
      - '*/*'
      description: It is a test of the database.
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/sysinfo.SysInfo'
      summary: It is a test of the database.
      tags:
      - root
  /info/save:
    get:
      consumes:
      - '*/*'
      description: It is a test of the database.
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/sysinfo.SysInfo'
      summary: It is a test of the database.
      tags:
      - root
  /notification/email:
    post:
      consumes:
      - application/json
      description: Send an email notification using the EmailService factory. Expects
        JSON data in the request body.
      parameters:
      - description: Email request
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/notification.sendEmailRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/notification.sendEmailResponse'
      summary: Send an email notification.
      tags:
      - notification
  /notification/sms:
    post:
      consumes:
      - application/json
      description: Using short message service from Twilio, sends a test notification
        to any number. Phone number in international format, example:"+123456789"
      parameters:
      - description: SMS request
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/notification.sendSMSRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/notification.sendEmailResponse'
      summary: Send an SMS notification.
      tags:
      - notification
  /servers:
    delete:
      consumes:
      - application/json
      description: delete  server from server id.
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: string
      summary: delete a server.
      tags:
      - server
    get:
      consumes:
      - '*/*'
      description: List all registered servers.
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/server.Server'
            type: array
      summary: Lists registered servers.
      tags:
      - server
    post:
      consumes:
      - application/json
      description: Creates new server for monitoring using a server struct as input.
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/server.Server'
      summary: Creates a new server.
      tags:
      - server
swagger: "2.0"
